### ISSUE TITLE
SwiftUI unexpected error

### ISSUE THREAD

**Issue by kutlueren** [Mattijah/QKMRZScanner#10]
Hi

I have been trying to use the library in SwiftUI. I have implemented and UIViewRepresentable and I was able to compile and run. However it crashes unexpectedly. I have attached the image that shows the error. I am running it ios 13.5. Here is the error message :

**2020-05-27 14:16:35.464742+0300 Kimlikizi[9223:1692248] Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file /Users/kaleuser/Desktop/KimlikIziMobile/ios/Kimlikizi/Pods/QKMRZScanner/QKMRZScanner/QKMRZScannerView.swift, line 34**

![Screen Shot 2020-05-27 at 14 22 02](https://user-images.githubusercontent.com/4067167/83013664-103f3280-a026-11ea-97cf-f4e45323780f.png)

**Comment by Mattijah** [comment]
Hi,

Thanks for the report. I have not optimised or even tested this library in SwiftUI. The problem however seems to be in the `QKCutoutView:draw` not being called and thus `cutoutRect` is not initialised (`nil`).

**Comment by kutlueren** [comment]
İs there any way that you can recommend to fix it? I like the library and want to use it if possible. Here is my struct :

```
import SwiftUI

import QKMRZScanner

struct QKMRZScanner: UIViewRepresentable {

    func makeCoordinator() -> Coordinator {

        Coordinator(self)

    }

    var mrzScannerView = QKMRZScannerView()

    class Coordinator: NSObject {

        var parent: QKMRZScanner

        init(_ mrzScannerView: QKMRZScanner) {

            self.parent = mrzScannerView

            super.init()
        }
    }

    func makeUIView(context: UIViewRepresentableContext<QKMRZScanner>) -> UIView {

        let view = QKMRZScannerView()

        return view
    }

    func updateUIView(_ uiView: UIView, context: UIViewRepresentableContext<QKMRZScanner>) {
        //mrzScannerView.delegate = self

        mrzScannerView.startScanning()
    }

    /*func mrzScannerView(_ mrzScannerView: QKMRZScannerView, didFind scanResult: QKMRZScanResult) {

        print(scanResult)

    }*/

}
```

**Comment by kutlueren** [comment]
I was able to make it work like below. I hope it helps to people.

```
import SwiftUI

import QKMRZScanner


struct QKMRZScanner: UIViewRepresentable {

    func makeCoordinator() -> Coordinator {

        Coordinator(self)

    }

    var mrzScannerView = QKMRZScannerView()

    class Coordinator: NSObject {

        var parent: QKMRZScanner

        init(_ mrzScannerView: QKMRZScanner) {

            self.parent = mrzScannerView

            super.init()

        }

    }

    func makeUIView(context: UIViewRepresentableContext<QKMRZScanner>) -> UIView {

        let view = UIView()

        mrzScannerView.contentMode = .scaleAspectFit

        mrzScannerView.translatesAutoresizingMaskIntoConstraints = false

        view.addSubview(mrzScannerView)

        NSLayoutConstraint.activate([

            mrzScannerView.widthAnchor.constraint(equalTo: view.widthAnchor),

            mrzScannerView.heightAnchor.constraint(equalTo: view.heightAnchor)

        ])

        return view

    }

    func updateUIView(_ uiView: UIView, context: UIViewRepresentableContext<QKMRZScanner>) {

        //mrzScannerView.delegate = self

        mrzScannerView.startScanning()

    }

    /*func mrzScannerView(_ mrzScannerView: QKMRZScannerView, didFind scanResult: QKMRZScanResult) {

        print(scanResult)

    }*/

}
```

**Comment by kutlueren** [comment]
However I was not able to implement QKMRZScannerViewDelegate since it expects a class to implement it. Any recommendation?

**Comment by Mattijah** [comment]
@kutlueren That's correct. Can't you make that struct simply a class? Or use some other class, it doesn't need to be `self`. (*I'm not that familiar with SwiftUI).

**Comment by kutlueren** [comment]
I have forked your repo and made a change like this; https://github.com/kutlueren/QKMRZScanner/commit/8c6a15aa19ef517bdf678391e64a177994133d8f#diff-5837d27931af443ac1ce5a317f7d86dc

it seems to be working but I don't know whether it would break on swift (previous versions of swiftUI). There seems to be another problem though with the version I changed, it parses MRZ but crashed afterward, I am looking into it maybe it is something I have done mistakenly.

**Comment by Mattijah** [comment]
> I have forked your repo and made a change like this; kutlueren@8c6a15a#diff-5837d27931af443ac1ce5a317f7d86dc

I don't think this really solves the problem. Why can't you just create a new class and assign its instance to delegate? Or make `QKMRZScanner` a class - if you need that? Won't that work in SwiftUI?

**Comment by kutlueren** [comment]
> > I have forked your repo and made a change like this; [kutlueren/QKMRZScanner@8c6a15a](https://github.com/kutlueren/QKMRZScanner/commit/8c6a15a)#diff-5837d27931af443ac1ce5a317f7d86dc
> 
> I don't think this really solves the problem. Why can't you just create a new class and assign its instance to delegate? Or make `QKMRZScanner` a class - if you need that? Won't that work in SwiftUI?

I doubt it. I am not uber good at swiftui, i have tried as you said though but could not get it compiled. If i create class then i can not implement uiviewrepresentable thus i can not use the library

**Comment by Mattijah** [comment]
Try simply something like this:

```swift
class QKMRZScannerViewHandler: QKMRZScannerViewDelegate {
    func mrzScannerView(_ mrzScannerView: QKMRZScannerView, didFind scanResult: QKMRZScanResult) {
        print(scanResult)
    }
}

struct QKMRZScanner: UIViewRepresentable {
    let handler = QKMRZScannerViewHandler()

    func updateUIView(_ uiView: UIView, context: UIViewRepresentableContext<QKMRZScanner>) {
        mrzScannerView.delegate = handler
    }
}
```

**Comment by kutlueren** [comment]
> Try simply something like this:
> 
> ```swift
> class QKMRZScannerViewHandler: QKMRZScannerViewDelegate {
>     func mrzScannerView(_ mrzScannerView: QKMRZScannerView, didFind scanResult: QKMRZScanResult) {
>         print(scanResult)
>     }
> }
> 
> struct QKMRZScanner: UIViewRepresentable {
>     let handler = QKMRZScannerViewHandler()
> 
>     func updateUIView(_ uiView: UIView, context: UIViewRepresentableContext<QKMRZScanner>) {
>         mrzScannerView.delegate = handler
>     }
> }
> ```

I will try that, seems simple and might work. I will get back with the result

**Comment by kutlueren** [comment]
> Try simply something like this:
> 
> ```swift
> class QKMRZScannerViewHandler: QKMRZScannerViewDelegate {
>     func mrzScannerView(_ mrzScannerView: QKMRZScannerView, didFind scanResult: QKMRZScanResult) {
>         print(scanResult)
>     }
> }
> 
> struct QKMRZScanner: UIViewRepresentable {
>     let handler = QKMRZScannerViewHandler()
> 
>     func updateUIView(_ uiView: UIView, context: UIViewRepresentableContext<QKMRZScanner>) {
>         mrzScannerView.delegate = handler
>     }
> }
> ```

It seems like working. I have been having a trouble getting QKMRZScanResult as a result out of QKMRZScannerViewHandler but it is another concern. Thank you for your help. If I can get it fully worked then I will publish it on GitHub and let you know.
