### ISSUE TITLE
Upgrade to a more recent version of SwiftTesseract

### ISSUE THREAD

**Issue by mehdi-S** [Mattijah/QKMRZScanner#14]
As the title says, is it possible to update your dependencies to use the latest version of swiftTesseract 5.3 ? 
It is now fully compatible with iOS 14 - XCode 12

**Comment by Mattijah** [comment]
I'll try to look into it over the weekend if I'm not too busy. `SwiftyTesseract` should certainly be updated regardless of if it's compatible with the new iOS & Xcode. Thanks!

**Comment by mehdi-S** [comment]
It seems that SwiftyTesseract moved to Swift Package manager only so it can only be added as a dependency via swift package manager, not pods anymore.
I've forked your repo, I'm trying to change the way you handle swiftyTesseract dependency by using Swift package manager, if I manage to succeed I'll sent you a PR

**Comment by mehdi-S** [comment]
I've trouble with SSL that prevent me from using package manager that I can't solve for the moment
here's the documentation that helped me setup the project for Swift Package Manager at least : 

https://github.com/SwiftyTesseract/SwiftyTesseract
https://swift.org/package-manager/

**Comment by Mattijah** [comment]
Alright, thanks

*So, sadly I didn't find any spare time this weekend to have a look at it, but I'm on it. It will be done. Just allow me a bit more time.

**Comment by Mattijah** [comment]
@mehdi-S Looks like there haven't even been a new release of SwiftyTesseract yet (`3.1.2` is the latest one currently). I will slowly integrate _Swift Package Manager_ and then update this dependency once available.
