### ISSUE TITLE
Can't complie on simulator - getting Undefined symbols for architecture x86_64 

### ISSUE THREAD

**Issue by dongmai** [Mattijah/QKMRZScanner#16]
I'm using QKMRZScanner version 2.2.1. I can complie fine on real devices no problem but simulator.

Can someone please help to check the log bellow:

`Undefined symbols for architecture x86_64:
  "_TessBaseAPIDelete", referenced from:
      SwiftyTesseract.SwiftyTesseract.deinit in SwiftyTesseract.o
  "_TessResultIteratorConfidence", referenced from:
      SwiftyTesseract.SwiftyTesseract.(block in _CF46D8508F77828387FBB1144906E91D)(from: Swift.OpaquePointer, for: __C.TessPageIteratorLevel) -> SwiftyTesseract.RecognizedBlock? in SwiftyTesseract.o
  "_pixDestroy", referenced from:
      $defer #1 () -> () in SwiftyTesseract.SwiftyTesseract.(render in _CF46D8508F77828387FBB1144906E91D)(_: [__C.UIImage], with: Swift.OpaquePointer) throws -> () in SwiftyTesseract.o
      (extension in SwiftyTesseract):Swift.Result< where A == Swift.UnsafeMutablePointer<__C.Pix>?>.(destroy in _CF46D8508F77828387FBB1144906E91D)() -> () in SwiftyTesseract.o
  "_TessPageIteratorDelete", referenced from:
      $defer #1 () -> () in SwiftyTesseract.SwiftyTesseract.recognizedBlocks(for: SwiftyTesseract.ResultIteratorLevel) -> Swift.Result<[SwiftyTesseract.RecognizedBlock], Swift.Error> in SwiftyTesseract.o
  "_TessPageIteratorNext", referenced from:
      SwiftyTesseract.SwiftyTesseract.recognizedBlocks(for: SwiftyTesseract.ResultIteratorLevel) -> Swift.Result<[SwiftyTesseract.RecognizedBlock], Swift.Error> in SwiftyTesseract.o
  "_TessResultRendererEndDocument", referenced from:
      SwiftyTesseract.SwiftyTesseract.(render in _CF46D8508F77828387FBB1144906E91D)(_: [__C.UIImage], with: Swift.OpaquePointer) throws -> () in SwiftyTesseract.o
  "_TessPageIteratorBoundingBox", referenced from:
      SwiftyTesseract.SwiftyTesseract.(makeBoundingBox in _CF46D8508F77828387FBB1144906E91D)(from: Swift.OpaquePointer, for: __C.TessPageIteratorLevel) -> SwiftyTesseract.BoundingBox in SwiftyTesseract.o
  "_TessDeleteResultRenderer", referenced from:
      SwiftyTesseract.SwiftyTesseract.(makeRenderer in _CF46D8508F77828387FBB1144906E91D)(at: Foundation.URL) throws -> Swift.OpaquePointer in SwiftyTesseract.o
      $defer #1 () -> () in SwiftyTesseract.SwiftyTesseract.(processPDF in _CF46D8508F77828387FBB1144906E91D)(images: [__C.UIImage]) throws -> Foundation.URL in SwiftyTesseract.o
  "_TessPDFRendererCreate", referenced from:
      SwiftyTesseract.SwiftyTesseract.(makeRenderer in _CF46D8508F77828387FBB1144906E91D)(at: Foundation.URL) throws -> Swift.OpaquePointer in SwiftyTesseract.o
  "_TessResultRendererBeginDocument", referenced from:
      SwiftyTesseract.SwiftyTesseract.(makeRenderer in _CF46D8508F77828387FBB1144906E91D)(at: Foundation.URL) throws -> Swift.OpaquePointer in SwiftyTesseract.o
  "_TessBaseAPIEnd", referenced from:
      SwiftyTesseract.SwiftyTesseract.deinit in SwiftyTesseract.o
  "_TessBaseAPISetSourceResolution", referenced from:
      closure #2 (Swift.UnsafeMutablePointer<__C.Pix>?) -> Swift.Result<Swift.String, Swift.Error> in SwiftyTesseract.SwiftyTesseract.performOCR(on: __C.UIImage) -> Swift.Result<Swift.String, Swift.Error> in SwiftyTesseract.o
  "_TessBaseAPICreate", referenced from:
      variable initialization expression of SwiftyTesseract.SwiftyTesseract.(tesseract in _CF46D8508F77828387FBB1144906E91D) : Swift.OpaquePointer in SwiftyTesseract.o
      SwiftyTesseract.SwiftyTesseract.(in _CF46D8508F77828387FBB1144906E91D).init(languageString: Swift.String, dataSource: SwiftyTesseract.LanguageModelDataSource, engineMode: SwiftyTesseract.EngineMode) -> SwiftyTesseract.SwiftyTesseract in SwiftyTesseract.o
  "_TessBaseAPIGetUTF8Text", referenced from:
      closure #2 (Swift.UnsafeMutablePointer<__C.Pix>?) -> Swift.Result<Swift.String, Swift.Error> in SwiftyTesseract.SwiftyTesseract.performOCR(on: __C.UIImage) -> Swift.Result<Swift.String, Swift.Error> in SwiftyTesseract.o
  "_TessBaseAPISetVariable", referenced from:
      SwiftyTesseract.SwiftyTesseract.(setTesseractVariable in _CF46D8508F77828387FBB1144906E91D)(_: SwiftyTesseract.TesseractVariableName, value: Swift.String) -> () in SwiftyTesseract.o
  "_pixReadMem", referenced from:
      SwiftyTesseract.SwiftyTesseract.(createPix in _CF46D8508F77828387FBB1144906E91D)(from: __C.UIImage) throws -> Swift.UnsafeMutablePointer<__C.Pix>? in SwiftyTesseract.o
  "_TessDeleteText", referenced from:
      $defer #1 () -> () in closure #2 (Swift.UnsafeMutablePointer<__C.Pix>?) -> Swift.Result<Swift.String, Swift.Error> in SwiftyTesseract.SwiftyTesseract.performOCR(on: __C.UIImage) -> Swift.Result<Swift.String, Swift.Error> in SwiftyTesseract.o
      $defer #1 () -> () in SwiftyTesseract.SwiftyTesseract.(block in _CF46D8508F77828387FBB1144906E91D)(from: Swift.OpaquePointer, for: __C.TessPageIteratorLevel) -> SwiftyTesseract.RecognizedBlock? in SwiftyTesseract.o
  "_TessBaseAPIGetIterator", referenced from:
      SwiftyTesseract.SwiftyTesseract.recognizedBlocks(for: SwiftyTesseract.ResultIteratorLevel) -> Swift.Result<[SwiftyTesseract.RecognizedBlock], Swift.Error> in SwiftyTesseract.o
  "_TessBaseAPIInit2", referenced from:
      SwiftyTesseract.SwiftyTesseract.(in _CF46D8508F77828387FBB1144906E91D).init(languageString: Swift.String, dataSource: SwiftyTesseract.LanguageModelDataSource, engineMode: SwiftyTesseract.EngineMode) -> SwiftyTesseract.SwiftyTesseract in SwiftyTesseract.o
  "_TessResultIteratorGetUTF8Text", referenced from:
      SwiftyTesseract.SwiftyTesseract.(block in _CF46D8508F77828387FBB1144906E91D)(from: Swift.OpaquePointer, for: __C.TessPageIteratorLevel) -> SwiftyTesseract.RecognizedBlock? in SwiftyTesseract.o
  "_TessBaseAPISetImage2", referenced from:
      closure #2 (Swift.UnsafeMutablePointer<__C.Pix>?) -> Swift.Result<Swift.String, Swift.Error> in SwiftyTesseract.SwiftyTesseract.performOCR(on: __C.UIImage) -> Swift.Result<Swift.String, Swift.Error> in SwiftyTesseract.o
  "_TessBaseAPIProcessPage", referenced from:
      closure #1 (Swift.Int, Swift.UnsafeMutablePointer<__C.Pix>?) throws -> () in SwiftyTesseract.SwiftyTesseract.(render in _CF46D8508F77828387FBB1144906E91D)(_: [__C.UIImage], with: Swift.OpaquePointer) throws -> () in SwiftyTesseract.o
  "_TessBaseAPIGetSourceYResolution", referenced from:
      closure #2 (Swift.UnsafeMutablePointer<__C.Pix>?) -> Swift.Result<Swift.String, Swift.Error> in SwiftyTesseract.SwiftyTesseract.performOCR(on: __C.UIImage) -> Swift.Result<Swift.String, Swift.Error> in SwiftyTesseract.o
  "_TessVersion", referenced from:
      closure #1 () -> Swift.String? in SwiftyTesseract.SwiftyTesseract.version.getter : Swift.String? in SwiftyTesseract.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by Mattijah** [comment]
Are you building the app with the new Xcode 12 and Cocoapods >= 1.10.0 as recommended in the Readme?

**Comment by dongmai** [comment]
oh sorry, I didnt read your Readme carefully. Its ok now, many thanks.
