### ISSUE TITLE
Is It possible to explicitly set desired document type for scan?

### ISSUE THREAD

**Issue by bugrym** [Mattijah/QKMRZScanner#17]
Hi. I use this scanner for different document types and faced with problem. I have to explicitly set desired doc type for scan, because in case when I wanna scan only ID, sometimes scanner determines that it's not ID and the same happen with Passport. Do any solution exist? Thanks.

**Comment by Mattijah** [comment]
Hi, could you please clarify further what to do you mean by the scanner not determining that the document is an ID (or passport)?

**Comment by bugrym** [comment]
So, I splitted the app flow for ID and passport. Since i can not set the desired document scan type before scan, I just check the document type which I receive in QKMRZScanResult and if it does not match previously selected option I just wanna warn user about it. During testing I found out that Scanner from time to time determines three line mrz as Passport and vice versa, two lines mrz as ID. As scanning options I just use simple enum like this: 
`enum DocType:String { 
case passport = "P", idCard = "ID" 
} `

**Comment by Mattijah** [comment]
Sorry for a delayed reply.

First of all, the user can also scan visas "_V_" or a driving license "_D_", so you should make sure your code can handle these appropriately too.

Regarding the second point, this looks rather like a bug. You should still however receive a correct document id (P/ID/V/D). Is that not the case? If so do you have any example I could test this with? Thanks

**Comment by bugrym** [comment]
Hi. Honestly, out app just does not support visas and driving licenses. I changed a bit existing flow so this issues is no longer exist. If you want me to reproduce bug, just contact me via email: 'vlad.bugrym@gmail.com' and I will help. Thanks for you answers!
