### ISSUE TITLE
Automation functional test is failing with simulator

### ISSUE THREAD

**Issue by naveen-kp-clt** [Mattijah/QKMRZScanner#20]
Hi,
I have used your codes and created one .framework file. I am planning to add the same .framework into my application for functional testing but its failing with simulator. So is there anyway to make this happen using swiftytesseract with simulator ?

**Comment by Mattijah** [comment]
I'm not really sure what exactly is the problem as you haven't posted any errors. Simulator is also not able to open/run camera, so maybe this is your problem?
