### ISSUE TITLE
Using GPU filters

### ISSUE THREAD

**Issue by nemesyssoft** [Mattijah/QKMRZScanner#22]
Hello.

Since you have absolutely no contact listed anywhere, I thought I would open an issue to get your attention.

I was just wondering why you came to choose the current GPU filters in GPUImage2 to achieve the scan. I'm trying to use your project at work to scan documents that sometimes have a plastic surface. The glare makes it very difficult to recognize anything. So, I was wondering why you chose the filters that you have and whether any would help with reducing the glare. Speaking of the filters, are there any reasons why your framework is so close in customizing the filters it uses and their values?

**Comment by Mattijah** [comment]
Hi @nemesyssoft, please excuse my rather brief response. I hope it will be at least a little useful though.

- There is no `GPUImage2` used in the current version of the library.
- The reason why we use a custom values (_configurations_) is simply, so we can achieve the best results.
- `LuminanceThresholdFilter` is a custom filter that had to be used for image processing. This filter is not available in `CoreImage`, so I had no other option but to create it myself.
- Removing glare from pictures can be a little tricky and there are multiple ways of doing it. For example: https://stackoverflow.com/questions/43470569/remove-glare-from-photo-opencv

**Comment by nemesyssoft** [comment]
Thank you!

-Laurent.
-- 
Laurent Daudelin				 						laurent@nemesys-soft.com <mailto:laurent@nemesys-soft.com>
Skype: LaurentDaudelin		
Logiciels Némésys Software			 				http://www.nemesys-soft.com/ <http://www.nemesys-soft.com/>
