### ISSUE TITLE
How to get Raw mrz text

### ISSUE THREAD

**Issue by janibekm** [Mattijah/QKMRZScanner#23]
Reader works fine, a few solution needed

1. View implementing xcode 12 error in storyboard
2. Raw MRZ text needed.

**Comment by Wilsonilo** [comment]
You can subclass or check the "QKMRZScannerView" class.
I think on line if let string = recognizedString is the main content String.

**Comment by janibekm** [comment]
> You can subclass or check the "QKMRZScannerView" class. I think on line if let string = recognizedString is the main content String.

Thank you fixed it
