### ISSUE TITLE
Missing Issue Date

### ISSUE THREAD

**Issue by MetaTouchDev** [Mattijah/QKMRZScanner#34]
Hello Mr. please update date of issue.
![Screenshot 2024-01-19 at 9 37 41 in the morning](https://github.com/Mattijah/QKMRZScanner/assets/157084036/80d93fb6-dfd3-4b96-b729-c4ce3c53d588)
![Screenshot 2024-01-19 at 9 37 06 in the morning](https://github.com/Mattijah/QKMRZScanner/assets/157084036/bd2ec933-5f93-400f-b43a-a96983bb8790)

**Comment by Mattijah** [comment]
The issuance date isn't present in the MRZ lines scanned, sadly. Depending on the document/country it's usually either -5 or -10 years. I can't really help here any more.

**Comment by MetaTouchDev** [comment]
I am so sad🥲
