### ISSUE TITLE
xCode 15.3 archiving error

### ISSUE THREAD

**Issue by emirbeytekin** [Mattijah/QKMRZScanner#35]
Hello,
I cannot assign the application to appstoreconnect due to libtesseract min target error
"The bundle Your.app/Frameworks/libtesseract.framework does not support the minimum OS Version specified in the Info.plist.

**Comment by Mattijah** [comment]
What is the minimum OS version you used?

**Comment by emirbeytekin** [comment]
> What is the minimum OS version you used?

iOS 13.1

**Comment by emirbeytekin** [comment]
is there a solution for this or should i look for another solution?

**Comment by Mattijah** [comment]
Hey, I haven't been able to look into this issue yet, but there error should kinda speak for itself: "_The bundle Your.app/Frameworks/libtesseract.framework does not support the minimum OS Version specified in the Info.plist_"

**Comment by emirbeytekin** [comment]
> Hey, I haven't been able to look into this issue yet, but there error should kinda speak for itself: "_The bundle Your.app/Frameworks/libtesseract.framework does not support the minimum OS Version specified in the Info.plist_"

I hope they update it or we will have to find another solution

**Comment by Frace17** [comment]
I have encountered the same issue, and it only appears in Xcode 15.3, is it Xcode bug? have you any suggestions?

**Comment by FilipNesic** [comment]
Hello, I am facing the same here "The bundle Your.app/Frameworks/libtesseract.framework does not support the minimum OS Version specified in the Info.plist." (Xcode 15.3) min target 16.0, even if I reduce OS Version to 10.13 in my project I am receiving the same archiving error.

**Comment by Mattijah** [comment]
Testing on Xcode 15.4, I am unable to reproduce this error. Everything works absolutely fine. The app runs and archiving also completes without errors.
