### ISSUE TITLE
kCVPixelFormatType_420YpCbCr8BiPlanarFullRange Causing CGImage Error

### ISSUE THREAD

**Issue by nicovert** [Mattijah/QKMRZScanner#38]
Using the master-spm branch (though the change seems to be in master as well) the recent change from `kCVPixelFormatType_32BGRA` to `kCVPixelFormatType_420YpCbCr8BiPlanarFullRange` seems to be causing CGContext.init in CVImageBuffer.swift to return nil.

Error message is the following:
```
CGBitmapContextCreate: invalid data bytes/row: should be at least 4320 for 8 integer bits/component, 3 components, kCGImageAlphaPremmultipliedFirst.
```

The issue is resolved when switching back to `kCVPixelFormatType_32BGRA`.

**Comment by Mattijah** [comment]
Will check this. 32BGRA is not really efficient. You should however be fetching a particular a release (this latest change has not been released yet)

**Comment by nicovert** [comment]
> You should however be fetching a particular a release (this latest change has not been released yet)

Is there a release with SPM/ARM support that doesn't also include that change?

**Comment by Mattijah** [comment]
As I mentioned, link to a particular version (release). The latest one doesn't include it. You are fetching entire master with changes that have not been released yet

**Comment by nicovert** [comment]
I see, but the latest release is not a swift package, correct? Only cocoa pods?

**Comment by Mattijah** [comment]
You are right, the SPM has not be released as a new version yet. I will make it primary the next time... You should still be able to refer to a particular commit in `master-spm`

**Comment by nicovert** [comment]
Understood, thank you!

**Comment by Mattijah** [comment]
Should be now fixed in: https://github.com/Mattijah/QKMRZScanner/commit/de9633e6f691c64fbbd010cb7a6e0ce2ddb477e3
