### ISSUE TITLE
The camera freezes after sometime

### ISSUE THREAD

**Issue by Dibyaa** [Mattijah/QKMRZScanner#5]
The camera freezes after giving a vibration after some time of scanning. There is neither error on the console nor output. Can you please see what the issue might be. I am attaching the screenshot of the phone and terminal.

![Screen Shot 2019-07-30 at 12 22 34 PM](https://user-images.githubusercontent.com/48793541/62106894-22e1c180-b2c6-11e9-94b1-cc8a6c858925.png)

![image1](https://user-images.githubusercontent.com/48793541/62106933-37be5500-b2c6-11e9-99d8-a99907e93547.png)

**Comment by Mattijah** [comment]
The vibration means that scanning was successful. In order to see the result you need to setup a delegate (see the readme). You are also not using the latest version of the module (2.1.1). What did you specify in your podfile?

**Comment by Dibyaa** [comment]
I had the following in my podfile as specified in the ReadMe.
pod 'QKMRZScanner'

However when I tried to install the module(2.1.1) is throws error as in the
picture.
Also, I have setup the delegate in my UIViewController as in the screenshot
below.
[image: Screen Shot 2019-07-30 at 2.49.16 PM.png]
[image: Screen Shot 2019-07-30 at 2.41.06 PM.png]

**Comment by Mattijah** [comment]
I'm not able to see your screenshots. Didn't you have this problem https://github.com/Mattijah/QKMRZScanner/issues/3 as well?

**Comment by Dibyaa** [comment]
No, I don't have the #3 problem. Both my project and pods are in swift 4.2 version. I'll resend the screenshots of my ViewController and the terminal below.
![Screen Shot 2019-07-30 at 2 49 16 PM](https://user-images.githubusercontent.com/48793541/62183218-094d8200-b379-11e9-8883-bc7be37e9699.png)

![Screen Shot 2019-07-30 at 2 41 06 PM](https://user-images.githubusercontent.com/48793541/62183246-2a15d780-b379-11e9-96a3-c36700e68d32.png)

**Comment by Mattijah** [comment]
Firstly, you didn't specify the delegate. 

```swift
override func viewDidLoad() {
     super.viewDidLoad()
     mrzScannerView.delegate = self // <<< <<< <<<
}
```

Secondly, as mentioned in the error message try to run: `pod repo update` and then `pod install`

**Comment by Dibyaa** [comment]
Hello sir,
The code works perfectly, thank you for your time and effort. Also, I am
really sorry for replying late.
