### ISSUE TITLE
Unable to subclass 'QKMRZScannerView'

### ISSUE THREAD

**Issue by SaurabhPrajapati** [Mattijah/QKMRZScanner#7]
Hey dear,

Thanks for such a nice library.

I want to modify it scannerView class a bit, but I'm not able to subclass it.
while subclassing, I'm getting below error

**"Cannot inherit from non-open class 'QKMRZScannerView' outside of its defining module'**

Can you please help me with this? (I don't want to make fork)

Thanks,
Saurabh Prajapati

**Comment by Mattijah** [comment]
The class `QKMRZScannerView` is marked as **public** which means it's _accessible_, but not _subclassable_ out of it's module. In order to be able to subclass it, it would need to be marked as **open** i.e `open class QKMRZScannerView: UIView`. What changes would you like to make?

**Comment by SaurabhPrajapati** [comment]
I just wanted to draw some borders around the scanning area and also want to make some other UI Changes according to my Project Theme.

**Comment by Mattijah** [comment]
`QKMRZScannerView` is a `UIView`, so this should allow you to do many UI changes just by calling `addSubview` and you should also be able to remove the default `QKCutoutView` if that's needed.

**Comment by SaurabhPrajapati** [comment]
I have tried - but if I'm adding sublayer or subview, then it is delaying the scan - I don't know why.

**Comment by Mattijah** [comment]
I have not been able to reproduce this issue. Also, you can add custom views to the ViewController's view (depends on your view structure), if `QKMRZScannerView` is not working well for you, but it most certainly should.
